### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by spectejb** [logicbomb/lvlTagEditor#1]
Hello!  Can you please add a license file with the license information?  Thank you!

**Comment by spectejb** [comment]
Hey @logicbomb - Just wanted to follow up on this request.  Thanks!

**Comment by logicbomb** [comment]
Thanks for the reminder, can you submit a PR with a license that suits your purposes?

**Comment by spectejb** [comment]
Sorry for the delay!  I was having access issues on my end but got everything straight and I just submitted the PR.  Thanks for your help!

**Comment by logicbomb** [comment]
no problem, merged.  i'm glad you find this useful!
